steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/prime-checker:$SHORT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/prime-checker:$SHORT_SHA' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy prime-checker \
          --image gcr.io/$PROJECT_ID/prime-checker:$SHORT_SHA \
          --region ${_REGION:-us-central1} \
          --platform managed \
          --allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/prime-checker:$SHORT_SHA'

substitutions:
  _REGION: "us-central1"
